/**: # wildcard for the node name
  ros__parameters:
    range_noise_stddev: 0.1    # in m
    process_noise_position_stddev: 0.1  # in m
    tag_0_pos:
      x1: 0.7   # [m]
      x2: 3.8   # [m]
      x3: -0.5  # [m]